// Clean, de-duplicated, and sensibly grouped by region.
// Fixed typos: "Earls-Court"→"Earl's Court", "Elephant Castle"→"Elephant & Castle",
// "Stand"→"Strand". Removed accidental duplicates (e.g., Manor Park only in East).
// Notes:
// - Some “central” landmarks (e.g., Baker Street, Strand, Westminster) are in Central London.
// - NW areas without a dedicated “North West” bucket are placed in North or West where appropriate.

export const LOCATIONS = [
  // ---------------- North London ----------------
  { name: "Archway", region: "north-london", desc: "Lively hub with strong community and great transport links." },
  { name: "Arsenal", region: "north-london", desc: "Home to Emirates Stadium and well-connected streets." },
  { name: "Barnet", region: "north-london", desc: "Suburban character with historic charm and green spaces." },
  { name: "Camden", region: "north-london", desc: "Markets, live music, and creative culture." },
  { name: "Colindale", region: "north-london", desc: "Growing district with new homes and parks." },
  { name: "Edgware", region: "north-london", desc: "Diverse centre with strong retail and amenities." },
  { name: "Enfield", region: "north-london", desc: "Green parks, heritage sites, and good links." },
  { name: "Finchley", region: "north-london", desc: "Residential area with cafés and schools." },
  { name: "Golders Green", region: "north-london", desc: "Multicultural vibe and nearby green spaces." },
  { name: "Hampstead", region: "north-london", desc: "Village feel near Hampstead Heath." },
  { name: "Harrow", region: "north-london", desc: "Busy town centre with renowned schools." },
  { name: "Hendon", region: "north-london", desc: "Home to RAF Museum and varied neighbourhoods." },
  { name: "Holloway", region: "north-london", desc: "Bustling high street and great transit." },
  { name: "Highbury", region: "north-london", desc: "Leafy streets and sports heritage." },
  { name: "Highgate", region: "north-london", desc: "Picturesque hilltop with historic charm." },
  { name: "Islington", region: "north-london", desc: "Boutiques, theatres, and dining on Upper Street." },
  { name: "Kentish Town", region: "north-london", desc: "Creative scene, venues, and markets." },
  { name: "Kilburn", region: "north-london", desc: "Lively high road and cultural mix." },
  { name: "Muswell Hill", region: "north-london", desc: "Elegant hilltop centre with views." },
  { name: "Seven Sisters", region: "north-london", desc: "Excellent links and local markets." },
  { name: "Tottenham", region: "north-london", desc: "Stadium area with strong community spirit." },
  { name: "Wood Green", region: "north-london", desc: "Shopping, entertainment, and transport hub." },

  // ---------------- East London ----------------
  { name: "Barking", region: "east-london", desc: "Rapidly developing with strong transport." },
  { name: "Bow", region: "east-london", desc: "Historic streets, cafés, and markets." },
  { name: "Bethnal Green", region: "east-london", desc: "Vibrant street life and nightlife." },
  { name: "Clapton", region: "east-london", desc: "Creative community close to parks." },
  { name: "Canary Wharf", region: "east-london", desc: "Skyscrapers, business, and waterfront dining." },
  { name: "Dagenham", region: "east-london", desc: "Residential area with industrial heritage." },
  { name: "Docklands", region: "east-london", desc: "Modern waterside developments." },
  { name: "East Ham", region: "east-london", desc: "Diverse high street and markets." },
  { name: "Hackney", region: "east-london", desc: "Creative hubs and nightlife." },
  { name: "Ilford", region: "east-london", desc: "Busy town centre and transport links." },
  { name: "Leyton", region: "east-london", desc: "Parks, sports, and growing cafés." },
  { name: "Limehouse", region: "east-london", desc: "Marina living near the City." },
  { name: "Manor Park", region: "east-london", desc: "Multicultural area with green spaces." },
  { name: "Newham", region: "east-london", desc: "Regeneration and excellent links." },
  { name: "Old Street", region: "east-london", desc: "Tech cluster on the City fringe." },
  { name: "Shoreditch", region: "east-london", desc: "Art, fashion, and dining hotspots." },
  { name: "Stratford", region: "east-london", desc: "Queen Elizabeth Olympic Park and shopping." },
  { name: "Tower Hamlets", region: "east-london", desc: "Historic riverside and modern towers." },
  { name: "Tower Hill", region: "east-london", desc: "City gateway by the Tower of London." },
  { name: "Walthamstow", region: "east-london", desc: "Village feel and market life." },
  { name: "West Ham", region: "east-london", desc: "Historic sports area and renewal." },
  { name: "Whitechapel", region: "east-london", desc: "Galleries, markets, and hospitals." },

  // ---------------- South West London ----------------
  { name: "Balham", region: "south-west-london", desc: "Cafés, parks, and family-friendly streets." },
  { name: "Barnes", region: "south-west-london", desc: "Riverside village charm." },
  { name: "Battersea", region: "south-west-london", desc: "Iconic power station and riverside living." },
  { name: "Chelsea", region: "south-west-london", desc: "Boutiques and galleries by the Thames." },
  { name: "Clapham", region: "south-west-london", desc: "Common-side living and nightlife." },
  { name: "Earl's Court", region: "south-west-london", desc: "Townhouses and great connections." },
  { name: "Fulham", region: "south-west-london", desc: "Riverside walks and village feel." },
  { name: "Pimlico", region: "south-west-london", desc: "Elegant terraces near the river." },
  { name: "Putney", region: "south-west-london", desc: "Rowing heritage and leafy avenues." },
  { name: "Wandsworth", region: "south-west-london", desc: "Parks and riverside regeneration." },
  { name: "Wimbledon", region: "south-west-london", desc: "Tennis, commons, and village centre." },
  { name: "Tooting", region: "south-west-london", desc: "Buzzing markets and eateries." },

  // ---------------- South East London ----------------
  { name: "Bermondsey", region: "south-east-london", desc: "Maltby Street, design, and riverside." },
  { name: "Blackheath", region: "south-east-london", desc: "Open heath and village feel." },
  { name: "Bromley", region: "south-east-london", desc: "Major town with retail and parks." },
  { name: "Camberwell", region: "south-east-london", desc: "Art schools and café culture." },
  { name: "Catford", region: "south-east-london", desc: "Community hubs and transport." },
  { name: "Charlton", region: "south-east-london", desc: "Riverside industry and heritage." },
  { name: "Crystal Palace", region: "south-east-london", desc: "Triangle dining and hilltop views." },
  { name: "Deptford", region: "south-east-london", desc: "Markets and creative spaces." },
  { name: "Dulwich", region: "south-east-london", desc: "Village, galleries, and parks." },
  { name: "Elephant & Castle", region: "south-east-london", desc: "Regeneration and transport hub." },
  { name: "Greenwich", region: "south-east-london", desc: "Maritime heritage and the park." },
  { name: "Lewisham", region: "south-east-london", desc: "Town centre regeneration." },
  { name: "New Cross", region: "south-east-london", desc: "Universities and music scene." },
  { name: "Plumstead", region: "south-east-london", desc: "Victorian streets and commons." },
  { name: "Southwark", region: "south-east-london", desc: "South Bank culture and eateries." },
  { name: "Sidcup", region: "south-east-london", desc: "Residential suburbs and colleges." },
  { name: "Surrey Quays", region: "south-east-london", desc: "Dockside living and retail." },
  { name: "Woolwich", region: "south-east-london", desc: "Elizabeth line links and riverside." },

  // ---------------- West London ----------------
  { name: "Acton", region: "west-london", desc: "Crossrail links and mixed neighbourhoods." },
  { name: "Alperton", region: "west-london", desc: "Canalside living with new builds." },
  { name: "Bayswater", region: "west-london", desc: "Townhouses by Hyde Park." },
  { name: "Chiswick", region: "west-london", desc: "Leafy, village feel and riverside pubs." },
  { name: "Ealing", region: "west-london", desc: "Parks, film history, and links." },
  { name: "Edgware Road", region: "west-london", desc: "Lively corridor into Central." },
  { name: "Hammersmith", region: "west-london", desc: "Riverside, venues, and offices." },
  { name: "Holland Park", region: "west-london", desc: "Elegant streets and the Kyoto Garden." },
  { name: "Kensington", region: "west-london", desc: "Museums, galleries, and garden squares." },
  { name: "Knightsbridge", region: "west-london", desc: "Luxury shopping and landmarks." },
  { name: "Lancaster Gate", region: "west-london", desc: "Grand terraces by the park." },
  { name: "Maida Vale", region: "west-london", desc: "Little Venice canals and mansions." },
  { name: "Notting Hill", region: "west-london", desc: "Pastel houses and Portobello Road." },
  { name: "Paddington", region: "west-london", desc: "Canals, stations, and new offices." },
  { name: "Park Royal", region: "west-london", desc: "Industrial hub with new homes." },
  { name: "Shepherd's Bush", region: "west-london", desc: "Westfield, music venues, and green." },
  { name: "Wembley", region: "west-london", desc: "Iconic stadium and events." },

  // ---------------- Central London ----------------
  { name: "Aldgate", region: "central-london", desc: "City gateway with modern offices." },
  { name: "Baker Street", region: "central-london", desc: "Sherlock Holmes and Marylebone vibe." },
  { name: "Bank", region: "central-london", desc: "Historic financial heart of the City." },
  { name: "Barbican", region: "central-london", desc: "Brutalist estate, arts centre, and gardens." },
  { name: "Belgravia", region: "central-london", desc: "Grand squares and embassies." },
  { name: "Charing Cross", region: "central-london", desc: "Transport node near Trafalgar Square." },
  { name: "Covent Garden", region: "central-london", desc: "Theatres, piazza, and dining." },
  { name: "Euston", region: "central-london", desc: "National rail and new campuses." },
  { name: "Farringdon", region: "central-london", desc: "Elizabeth line hub and eateries." },
  { name: "Holborn", region: "central-london", desc: "Legal quarter and offices." },
  { name: "King's Cross", region: "central-london", desc: "Regenerated canal-side district." },
  { name: "Mayfair", region: "central-london", desc: "Luxury hotels, galleries, and retail." },
  { name: "Soho", region: "central-london", desc: "Media, nightlife, and dining." },
  { name: "Strand", region: "central-london", desc: "Historic avenue linking City to West End." },
  { name: "Victoria", region: "central-london", desc: "Major station and new offices." },
  { name: "Waterloo", region: "central-london", desc: "South Bank arts and big station." },
  { name: "Westminster", region: "central-london", desc: "Government, Abbey, and landmarks." },
  { name: "London Bridge", region: "central-london", desc: "Markets and Shard on the river." },

  // ---------------- Greater London (outer & nearby) ----------------
  { name: "Croydon", region: "greater-london", desc: "South London hub with skyline growth." },
  { name: "Hayes", region: "greater-london", desc: "Crossrail links and industry." },
  { name: "Heathrow", region: "greater-london", desc: "International airport and business parks." },
  { name: "Hounslow", region: "greater-london", desc: "West suburban centre near the A4." },
  { name: "Isleworth", region: "greater-london", desc: "Riverside living and heritage." },
  { name: "Northolt", region: "greater-london", desc: "Suburban streets and RAF history." },
  { name: "Morden", region: "greater-london", desc: "Northern line terminus with parks." },
  { name: "Richmond", region: "greater-london", desc: "River, park, and historic centre." },
  { name: "Roehampton", region: "greater-london", desc: "Green campus and village feel." },
  { name: "Ruislip", region: "greater-london", desc: "Suburban town with lido and woods." },
  { name: "Slough", region: "greater-london", desc: "Nearby Berkshire business centre." },
  { name: "Twickenham", region: "greater-london", desc: "Rugby heartland by the Thames." },
  { name: "Watford", region: "greater-london", desc: "Hertfordshire town just outside London." },
];
